### PR TITLE
More VacBot commands implemented, Wait moved from VacBot to CLI

### PR DESCRIPTION
**Pull request by Zenconomy**
Commands for
- spot cleaning
- move
- request states for battery, clean, charge
- get and set the robot's time

Wait timer also moved from VacBot to CLI as timing of commands makes more sense to keep implementation specific (for example, an event-driven application may not implement timers at all)

### CODE REVIEW

**Comment by wpietri** [comment]
I think I like where you're going with this, but I think you've dropped some functionality here.

The Charge and Stop commands both wait until the vacuum has actually completed the action. That's valuable to me so that I can see the full log of its journey. I'm not opposed to moving that to the CLI, but I'd like to hear @OverloadUT's take on his intended use in a library setting.

**Comment by wpietri** [comment]
Also, I'd like to you to say a bit more about why you'd like to move all timing things to the client. Is the notion that you'd like a more primitive set of commands, ones more closely akin to the robot protocol? My theory of them was more along the lines of user requests. There's definitely some overlap there, but to me the Clean object is really "clean for X seconds", not "start cleaning mode". I'm willing to change that, or to separate the concerns more, but I'm wondering about the specific use case that motivates the change.

**Comment by Zenconomy** [comment]
Ah I see, you're logging when the action is completed. I like the idea of a full log of the robot's journey! With the event functionality in place we could easily implement a log that stores every issued command, every action the robot takes and errors it emits in a log with timestamp. I'd love to have that.

Definitely worth discussing where timing functionality belongs. My reasoning is that for simplicity the base VacBot class should deal with the communication with the robot, but not implement behaviours beyond that. Better to abstract such things and put them in a separate class.

In your CLI implementation, the queue of upcoming commands is managed by the CLI, but the wait between commands is managed by the VacBot Class.  Maybe it would make sense to abstract those functions to a separate scheduling class that manages the queue of commands with wait times, has methods for pause/resume/abort and triggers for when events (errors or state updates) occur?

Use cases:
- being able to pause/resume execution from the client
- being able to fire an event handler when the robot gets stuck, that for example tries to get unstuck and then resumes the previous command. Or pauses and sends an alert to the owner.
- being able to set other triggers than time, such as clean until we reach 50% battery, then spot clean until 20% battery, then dock
- being able to log when the robot has docked :)

Would love to hear your thoughts!

**Comment by OverloadUT** [comment]
> the base VacBot class should deal with the communication with the robot, but not implement behaviours beyond that.

I completely agree with this. When I call the library to tell the bot to go home, I want it to return as soon as possible and tell me if the command was issued.

> There's definitely some overlap there, but to me the Clean object is really "clean for X seconds", not "start cleaning mode".

I absolutely only want the second one. In the Home Assistant world, Home Assistant is the boss. It's the connector of all of the bits and pieces and does all of the logic to make it all smart. To clean for 30 minutes and then stop, I'd want Home Assistant to issue the start and then later the go-home command. This way, plenty of additional logic could sit in between there: Maybe we want to clean until the battery is at 75%? Maybe we want to clean, but stop when any resident is 5 minutes away from home so the robot is back home by the time anyone walks in the door?

As for use-cases, mine pretty much mirror @Zenconomy's exactly.

**Comment by wpietri** [comment]
Fab. That's very helpful. If it's only the command line app that is thinking about it in those terms, then yes, the waiting should definitely get pulled out of the library. I want to do that without losing functionality, which will take me a bit of work.

In the meantime, @Zenconomy, could you resubmit this PR as containing just the new commands you'd like to add? I don't want to lose that. But before you do, please also add unit tests. We should add no new functionality without corresponding tests. Otherwise it's too easy for some future PR-submitter to break things you wanted to work.

**Pull request closed without merging**
